apiVersion: apps/v1
kind: Deployment
metadata:
  name: atino-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atino
  template:
    metadata:
      labels:
        app: atino
    spec:
      containers:
        - name: atino-container
          image: nguyentrachminh/atino:v2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: atino-service
spec:
  type: LoadBalancer
  selector:
    app: atino
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
