apiVersion: apps/v1
kind: Deployment
metadata:
  name: atino-deployment
  labels:
    app: atino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atino
  template:
    metadata:
      labels:
        app: atino
    spec:
      containers:
      - name: atino
        image: YOUR_DOCKERHUB_USERNAME/atino:v1.1  # CI/CD sẽ tự động tăng version
        ports:
        - containerPort: 80
